"""ComfyUI-DDHT-AnyNode custom node package."""

from .clip_management import (
    NODE_CLASS_MAPPINGS as CLIP_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as CLIP_NODE_DISPLAY_NAME_MAPPINGS,
)
from .deepseek_api import (
    NODE_CLASS_MAPPINGS as DEEPSEEK_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as DEEPSEEK_NODE_DISPLAY_NAME_MAPPINGS,
)
from .folder_images import (
    NODE_CLASS_MAPPINGS as IMAGE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as IMAGE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .local_llm import (
    NODE_CLASS_MAPPINGS as LLM_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LLM_NODE_DISPLAY_NAME_MAPPINGS,
)
from .nodes import (
    NODE_CLASS_MAPPINGS as CORE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as CORE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .sla_attention import (
    NODE_CLASS_MAPPINGS as SLA_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SLA_NODE_DISPLAY_NAME_MAPPINGS,
)
from .text_validation import (
    NODE_CLASS_MAPPINGS as TEXT_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as TEXT_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **IMAGE_NODE_CLASS_MAPPINGS,
    **DEEPSEEK_NODE_CLASS_MAPPINGS,
    **CORE_NODE_CLASS_MAPPINGS,
    **CLIP_NODE_CLASS_MAPPINGS,
    **LLM_NODE_CLASS_MAPPINGS,
    **SLA_NODE_CLASS_MAPPINGS,
    **TEXT_NODE_CLASS_MAPPINGS,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    **IMAGE_NODE_DISPLAY_NAME_MAPPINGS,
    **DEEPSEEK_NODE_DISPLAY_NAME_MAPPINGS,
    **CORE_NODE_DISPLAY_NAME_MAPPINGS,
    **CLIP_NODE_DISPLAY_NAME_MAPPINGS,
    **LLM_NODE_DISPLAY_NAME_MAPPINGS,
    **SLA_NODE_DISPLAY_NAME_MAPPINGS,
    **TEXT_NODE_DISPLAY_NAME_MAPPINGS,
}

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
